### ISSUE TITLE
[skip/addon] Segfault in `SKStore.Handle::getArray()`.

### ISSUE THREAD

**Issue by beauby** [SkipLabs/skip#633]
Repro:
```
$ make nodeclient-database  # This should fail the first time, but  not segfault.
$ make nodeclient-database  # This should segfault the second time (provided the addon is loaded).
```

Stacktrace:
```
#0  sk.SKStore_Handle__getArray.6(void) () at /home/beauby/Code/skfs/skiplang/prelude/src/skstore/Handle.sk:331
#1  0x00007ffff42c7105 in SKStore.Handle<SKStore.SID, SkipRuntime.ResourceDef>::maybeGet () at /home/beauby/Code/skfs/skiplang/prelude/src/skstore/Handle.sk:351
#2  sk.SkipRuntime_createReactiveResource(void) () at /home/beauby/Code/skfs/skipruntime-ts/native/src/Runtime.sk:1468
#3  0x00007ffff42c948e in sk.SkipRuntime_getAll(void) () at /home/beauby/Code/skfs/skipruntime-ts/native/src/Runtime.sk:1211
#4  0x00007ffff42cb790 in sk.SkipRuntime_getAllOfRuntime__Closure0__call () at /home/beauby/Code/skfs/skipruntime-ts/native/src/Extern.sk:618
#5  0x00007ffff42acf31 in vtry__Closure0__call () at /home/beauby/Code/skfs/skiplang/prelude/src/core/language/Exception.sk:126
#6  0x00007ffff427171d in SKIP_etry () from /home/beauby/Code/skfs/skipruntime-ts/addon/dist/libskip-runtime-ts-x64-linux.so
#7  0x00007ffff42defa7 in sk.vtry.6(void) () at /home/beauby/Code/skfs/skiplang/prelude/src/core/language/Exception.sk:124
#8  0x00007ffff42df5c9 in SkipRuntime_Runtime__getAll () at /home/beauby/Code/skfs/skipruntime-ts/native/src/Extern.sk:617
#9  0x00007ffff43926f5 in std::_Function_handler<void (v8::Isolate*), skipruntime::GetAllOfRuntime(v8::FunctionCallbackInfo<v8::Value> const&)::{lambda(v8::Isolate*)#1}>::_M_invoke(std::_Any_data const&, v8::Isolate*&&) () from /home/beauby/Code/skfs/skipruntime-ts/addon/build/Release/skip_runtime.node
#10 0x00007ffff4389cb8 in skbinding::NatTryCatch(v8::Isolate*, std::function<void (v8::Isolate*)>) () from /home/beauby/Code/skfs/skipruntime-ts/addon/build/Release/skip_runtime.node
#11 0x00007ffff438f5a5 in skipruntime::GetAllOfRuntime(v8::FunctionCallbackInfo<v8::Value> const&) () from /home/beauby/Code/skfs/skipruntime-ts/addon/build/Release/skip_runtime.node
#12 0x00005554f6b4f5e2 in ?? ()
#13 0x00007fffffff7f28 in ?? ()
#14 0x00007fffffff7f60 in ?? ()
#15 0x0000000000000003 in ?? ()
#16 0x0000000000000068 in ?? ()
#17 0x00007fffffff7ed0 in ?? ()
#18 0x0000000000000036 in ?? ()
#19 0x00007fffffff8020 in ?? ()
#20 0x00005554f6b4d8de in ?? ()
#21 0x00003cdd70128531 in ?? ()
#22 0x0000000300000000 in ?? ()
#23 0x00000ab4ced41231 in ?? ()
#24 0x000009f1356fb921 in ?? ()
#25 0x000055555898c000 in ?? ()
#26 0x000029b9a4b80069 in ?? ()
#27 0x000029b9a4b80069 in ?? ()
#28 0x000029b9a4b80069 in ?? ()
#29 0x000029b9a4b80069 in ?? ()
#30 0x000009f1356fb921 in ?? ()
#31 0x00001a92c9375ef9 in ?? ()
#32 0x00001a92c9376c71 in ?? ()
#33 0x00001a92c9376e59 in ?? ()
#34 0x00001a92c9375dc9 in ?? ()
#35 0x00001a92c9375ef9 in ?? ()
#36 0x00001a92c9376701 in ?? ()
#37 0x000009f1356ddc21 in ?? ()
#38 0x00001a92c9376c91 in ?? ()
#39 0x000009f1356dd289 in ?? ()
#40 0x0000000500000000 in ?? ()
#41 0x000009f1356fb921 in ?? ()
#42 0x00001a92c9376e59 in ?? ()
#43 0x00001a92c9376c71 in ?? ()
#44 0x00001a92c9375ef9 in ?? ()
#45 0x000009f1356fb921 in ?? ()
#46 0x00003cdd701285d9 in ?? ()
#47 0x000009f1356fb891 in ?? ()
#48 0x00000e96fc796129 in ?? ()
#49 0x000029b9a4b80069 in ?? ()
#50 0x000000fb00000000 in ?? ()
#51 0x0000192ea241b079 in ?? ()
#52 0x0000000000000001 in ?? ()
#53 0x00001a92c9376851 in ?? ()
#54 0x00001a92c9376811 in ?? ()
#55 0x00007fffffff8090 in ?? ()
#56 0x00005554f6b4d8de in ?? ()
#57 0x000029b9a4b80069 in ?? ()
#58 0x000009f1356dd4f1 in ?? ()
#59 0x000009f1356dd4c1 in ?? ()
#60 0x00001a4974d83f01 in ?? ()
#61 0x000029b9a4b80069 in ?? ()
#62 0x00001a92c9376851 in ?? ()
#63 0x000029b9a4b80069 in ?? ()
#64 0x0000009000000000 in ?? ()
#65 0x0000192ea241ad31 in ?? ()
#66 0x0000000000000004 in ?? ()
#67 0x00003ac924a1dae9 in ?? ()
#68 0x00001a92c9376811 in ?? ()
#69 0x00007fffffff8130 in ?? ()
#70 0x00005554f6b4d8de in ?? ()
#71 0x000009f1356ddc21 in ?? ()
#72 0x00001a92c9375ef9 in ?? ()
#73 0x00001a92c9375dc9 in ?? ()
#74 0x00001a92c9376701 in ?? ()
#75 0x00001a92c9376701 in ?? ()
#76 0x00001a92c9375dc9 in ?? ()
#77 0x00001a92c9375ef9 in ?? ()
#78 0x000009f1356ddc21 in ?? ()
#79 0x00003ac924a1dae9 in ?? ()
#80 0x00001a92c93766d9 in ?? ()
#81 0x000009f1356ddce9 in ?? ()
#82 0x00001a92c9376701 in ?? ()
#83 0x000029b9a4b80069 in ?? ()
#84 0x0000007f00000000 in ?? ()
#85 0x0000192ea241abc1 in ?? ()
#86 0x0000000000000004 in ?? ()
#87 0x00001a4974dba9e1 in ?? ()
#88 0x00001a92c93766d9 in ?? ()
#89 0x00007fffffff81c0 in ?? ()
#90 0x00005554d6dcc899 in ?? ()
#91 0x000029b9a4b80069 in ?? ()
#92 0x00001a92c9370851 in ?? ()
#93 0x00001a92c9370c19 in ?? ()
#94 0x00001a92c9376681 in ?? ()
#95 0x00001a92c9376681 in ?? ()
#96 0x00001a92c9370c19 in ?? ()
#97 0x00001a92c9370851 in ?? ()
#98 0x000029b9a4b80069 in ?? ()
#99 0x00002fda3210f889 in ?? ()
#100 0x00001a4974dba9e1 in ?? ()
#101 0x00000d102a8a7881 in ?? ()
#102 0x000038233a7faa21 in ?? ()
#103 0x0000192ea2403651 in ?? ()
#104 0x0000000000000004 in ?? ()
#105 0x000038233a7fb359 in ?? ()
#106 0x00002fda3210f889 in ?? ()
#107 0x00007fffffff8258 in ?? ()
#108 0x00005554f6b4d8de in ?? ()
#109 0x00001a4974da6291 in ?? ()
#110 0x00001a92c9370851 in ?? ()
#111 0x00001a92c9370c19 in ?? ()
#112 0x00001a92c9376681 in ?? ()
#113 0x000029b9a4b80069 in ?? ()
#114 0x00001a92c9376681 in ?? ()
#115 0x00001a92c9370c19 in ?? ()
#116 0x00001a92c9370851 in ?? ()
#117 0x00001a4974da6291 in ?? ()
#118 0x000038233a7fb359 in ?? ()
#119 0x00001a4974da6291 in ?? ()
#120 0x000029b9a4b80069 in ?? ()
#121 0x000000e600000000 in ?? ()
#122 0x0000192ea240cc19 in ?? ()
#123 0x0000000000000001 in ?? ()
#124 0x00001a92c9376681 in ?? ()
#125 0x00001a92c9376621 in ?? ()
#126 0x00007fffffff82c0 in ?? ()
#127 0x00005554f6b4d8de in ?? ()
#128 0x000029b9a4b80069 in ?? ()
#129 0x000029b9a4b80069 in ?? ()
#130 0x00003ac924a1f3f1 in ?? ()
#131 0x00001a92c9376681 in ?? ()
#132 0x00002fda32111249 in ?? ()
#133 0x000029b9a4b80069 in ?? ()
#134 0x000000c300000000 in ?? ()
#135 0x0000192ea240cab1 in ?? ()
#136 0x0000000000000004 in ?? ()
#137 0x000038233a7fcbf9 in ?? ()
#138 0x00001a92c9376621 in ?? ()
#139 0x00007fffffff8350 in ?? ()
#140 0x00005554d6dcc899 in ?? ()
#141 0x00001a4974d9f871 in ?? ()
#142 0x00001a92c9370851 in ?? ()
#143 0x00001a92c9370c19 in ?? ()
#144 0x00001a92c9371419 in ?? ()
#145 0x00001a92c9371419 in ?? ()
#146 0x00001a92c9370c19 in ?? ()
#147 0x00001a92c9370851 in ?? ()
#148 0x000029b9a4b80069 in ?? ()
#149 0x00002fda3210f889 in ?? ()
#150 0x00001a4974db7581 in ?? ()
#151 0x00000d102a8a7881 in ?? ()
#152 0x000038233a7faa21 in ?? ()
#153 0x0000192ea2403651 in ?? ()
#154 0x0000000000000004 in ?? ()
#155 0x000038233a7fb359 in ?? ()
#156 0x00002fda3210f889 in ?? ()
#157 0x00007fffffff83d8 in ?? ()
#158 0x00005554d6dcf607 in ?? ()
#159 0x00001a4974dab839 in ?? ()
#160 0x00001a92c9370851 in ?? ()
#161 0x00001a92c9370c19 in ?? ()
#162 0x00001a92c9371419 in ?? ()
#163 0x00001a92c9371419 in ?? ()
#164 0x00001a92c9370c19 in ?? ()
#165 0x00001a92c9370851 in ?? ()
#166 0x00001a4974dab839 in ?? ()
#167 0x000038233a7fb359 in ?? ()
#168 0x00000d102a8a8d41 in ?? ()
#169 0x0000302879af48c9 in ?? ()
#170 0x0000192ea2403271 in ?? ()
#171 0x0000000000000001 in ?? ()
#172 0x00001a92c93764c9 in ?? ()
#173 0x00001a92c9375df1 in ?? ()
#174 0x00007fffffff8440 in ?? ()
#175 0x00005554f6b4d8de in ?? ()
#176 0x000029b9a4b80069 in ?? ()
#177 0x000029b9a4b80069 in ?? ()
#178 0x000029b9a4b80069 in ?? ()
#179 0x00001a4974db02f9 in ?? ()
#180 0x00001a92c93764c9 in ?? ()
#181 0x000029b9a4b80069 in ?? ()
#182 0x0000005d00000000 in ?? ()
#183 0x0000192ea240c891 in ?? ()
#184 0x0000000000000001 in ?? ()
#185 0x00001a92c93765a1 in ?? ()
#186 0x00001a92c9376509 in ?? ()
#187 0x00007fffffff84a8 in ?? ()
#188 0x00005554f6b4d8de in ?? ()
#189 0x000029b9a4b80069 in ?? ()
#190 0x000029b9a4b80069 in ?? ()
#191 0x000029b9a4b80069 in ?? ()
#192 0x0000000000000000 in ?? ()
```

**Comment by mbouaziz** [comment]
Related #634

**Comment by beauby** [comment]
@skiplabsdaniel Was this fixed by #638?

**Comment by skiplabsdaniel** [comment]
The #638 ensures that this no longer happens, but it seems that the underlying problem is still there.
I'll have to check if this also happens with the wasm version.

**Comment by beauby** [comment]
@skiplabsdaniel Datapoint: at the time of opening this issue, the exact same setting with the wasm runtime instead of the addon did _not_ crash.

**Comment by skiplabsdaniel** [comment]
@beauby It's because the problem resolve by #638 never happens in `wasm`.
